<a href="https://colab.research.google.com/github/pranta2003/kaggle-ml-projects/blob/main/Lab3_insurence_dataPreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/My_Files/insurance_data.csv')

In [ ]:
dataset

age  affordibility  bought_insurance
0    22              1                 0
1    25              0                 0
2    47              1                 1
3    52              0                 0
4    46              1                 1
5    56              1                 1
6    55              0                 0
7    60              0                 1
8    62              1                 1
9    61              1                 1
10   18              1                 0
11   28              1                 0
12   27              0                 0
13   29              0                 0
14   49              1                 1
15   55              1                 1
16   25              0                 1
17   58              1                 1
18   19              0                 0
19   18              1                 0
20   21              1                 0
21   26              0                 0
22   40              1                 1
23   45              1                 1
24   50              1                 1
25   54              1                 1
26   23              1                 0
27   46              1                 0

In [ ]:
x=dataset.iloc[:, :-1]

In [ ]:
x

age  affordibility
0    22              1
1    25              0
2    47              1
3    52              0
4    46              1
5    56              1
6    55              0
7    60              0
8    62              1
9    61              1
10   18              1
11   28              1
12   27              0
13   29              0
14   49              1
15   55              1
16   25              0
17   58              1
18   19              0
19   18              1
20   21              1
21   26              0
22   40              1
23   45              1
24   50              1
25   54              1
26   23              1
27   46              1

In [ ]:
y=dataset.iloc[:, -1]

In [ ]:
y

0     0
1     0
2     1
3     0
4     1
5     1
6     0
7     1
8     1
9     1
10    0
11    0
12    0
13    0
14    1
15    1
16    1
17    1
18    0
19    0
20    0
21    0
22    1
23    1
24    1
25    1
26    0
27    0
Name: bought_insurance, dtype: int64

In [ ]:
x=dataset.iloc[:, :-1].values
y=dataset.iloc[:, -1].values

In [ ]:
x
y

array([0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0])

In [ ]:
x

array([[22,  1],
       [25,  0],
       [47,  1],
       [52,  0],
       [46,  1],
       [56,  1],
       [55,  0],
       [60,  0],
       [62,  1],
       [61,  1],
       [18,  1],
       [28,  1],
       [27,  0],
       [29,  0],
       [49,  1],
       [55,  1],
       [25,  0],
       [58,  1],
       [19,  0],
       [18,  1],
       [21,  1],
       [26,  0],
       [40,  1],
       [45,  1],
       [50,  1],
       [54,  1],
       [23,  1],
       [46,  1]])

In [ ]:
y

array([0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0])

In [ ]:
print(x)

[[22  1]
 [25  0]
 [47  1]
 [52  0]
 [46  1]
 [56  1]
 [55  0]
 [60  0]
 [62  1]
 [61  1]
 [18  1]
 [28  1]
 [27  0]
 [29  0]
 [49  1]
 [55  1]
 [25  0]
 [58  1]
 [19  0]
 [18  1]
 [21  1]
 [26  0]
 [40  1]
 [45  1]
 [50  1]
 [54  1]
 [23  1]
 [46  1]]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [ ]:
print(x_train)

[[40  1]
 [18  1]
 [26  0]
 [46  1]
 [47  1]
 [45  1]
 [55  0]
 [19  0]
 [29  0]
 [60  0]
 [54  1]
 [25  0]
 [25  0]
 [22  1]
 [55  1]
 [46  1]
 [23  1]
 [61  1]
 [62  1]
 [27  0]
 [28  1]
 [56  1]]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

x_train[:, :] = sc.fit_transform(x_train[:, :])
x_test[:, :] = sc.transform(x_test[:, :])

In [ ]:
print